/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DSA;

import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        String[] s = {"1", "2", "15", "-7", "300"};
        Arrays.sort(s);
        System.out.println(Arrays.toString(s));
    }
}
